import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableRolesMenuPermission1750210853799 implements MigrationInterface {
    name = 'CreateTableRolesMenuPermission1750210853799'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "menus" DROP CONSTRAINT "FK_00ccc1ed4e9fc23bc1246269359"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_b9bcaf1da5095642dc631ffbabf"`);
        await queryRunner.query(`CREATE TABLE "role_menus" ("role_id" integer NOT NULL, "menu_id" integer NOT NULL, CONSTRAINT "PK_0c02205fabd207a919cb7833813" PRIMARY KEY ("role_id", "menu_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cec0c62317111ac45c9c295d22" ON "role_menus" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c7c7bd4eb8a33aece58434cbf" ON "role_menus" ("menu_id") `);
        await queryRunner.query(`ALTER TABLE "menus" DROP CONSTRAINT "UQ_2aba70b42a11fed06c5ad55865e"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "path"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "icon"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "parent_id"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "order"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "permission_type"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_permission_type_enum"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "price" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "category" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "action" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "menuId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "roleId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "menus" DROP CONSTRAINT "PK_3fec3d93327f4538e0cbd4349c4"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menus" ADD CONSTRAINT "PK_3fec3d93327f4538e0cbd4349c4" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role_id" integer`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_f10931e7bb05a3b434642ed2797"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "PK_c1433d71a4838793a49dcad46ab"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "PK_920331560282b8bd21bb02290df"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "menu_id"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "menu_id" integer`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "role_id" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_b9bcaf1da5095642dc631ffbabf" FOREIGN KEY ("menu_id") REFERENCES "menus"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_f10931e7bb05a3b434642ed2797" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_menus" ADD CONSTRAINT "FK_cec0c62317111ac45c9c295d226" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_menus" ADD CONSTRAINT "FK_4c7c7bd4eb8a33aece58434cbf5" FOREIGN KEY ("menu_id") REFERENCES "menus"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_menus" DROP CONSTRAINT "FK_4c7c7bd4eb8a33aece58434cbf5"`);
        await queryRunner.query(`ALTER TABLE "role_menus" DROP CONSTRAINT "FK_cec0c62317111ac45c9c295d226"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_f10931e7bb05a3b434642ed2797"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_b9bcaf1da5095642dc631ffbabf"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "role_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "menu_id"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "menu_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "PK_920331560282b8bd21bb02290df"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "PK_c1433d71a4838793a49dcad46ab"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_f10931e7bb05a3b434642ed2797" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menus" DROP CONSTRAINT "PK_3fec3d93327f4538e0cbd4349c4"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "menus" ADD CONSTRAINT "PK_3fec3d93327f4538e0cbd4349c4" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "roleId"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "menuId"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_permission_type_enum" AS ENUM('view', 'create', 'update', 'delete', 'manage')`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "permission_type" "public"."permissions_permission_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "order" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "parent_id" uuid`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "icon" character varying`);
        await queryRunner.query(`ALTER TABLE "menus" ADD "path" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menus" ADD CONSTRAINT "UQ_2aba70b42a11fed06c5ad55865e" UNIQUE ("path")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c7c7bd4eb8a33aece58434cbf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cec0c62317111ac45c9c295d22"`);
        await queryRunner.query(`DROP TABLE "role_menus"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_b9bcaf1da5095642dc631ffbabf" FOREIGN KEY ("menu_id") REFERENCES "menus"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menus" ADD CONSTRAINT "FK_00ccc1ed4e9fc23bc1246269359" FOREIGN KEY ("parent_id") REFERENCES "menus"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
